require 'pry'
require 'rest-client'
require 'json'
require 'nokogiri'
require 'open-uri'

require_relative './food_recipes/version'
require_relative './food_recipes/cli'
require_relative './food_recipes/recipe'
require_relative './food_recipes/scraper'